version: '3.8'

services:
    app:
        image: laravel:latest
        container_name: laravel_app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - ./:/var/www/html
        networks:
            - app-network
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=base64:your-app-key
            - DB_CONNECTION=pgsql
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=laravel
            - DB_USERNAME=user
            - DB_PASSWORD=password
        depends_on:
            - db

    db:
        image: postgres:latest
        container_name: postgres_db
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        ports:
            - "5432:5432"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    pgdata:
