version: '3.8'

services:
    app:
        image: laravel:latest
        container_name: laravel_app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - ./:/var/www/html
        networks:
            - app-network
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=base64:your-app-key

networks:
    app-network:
        driver: bridge
